# Generated by Django 5.2.5 on 2025-11-19 18:38

import beaches.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Task', max_length=200)),
                ('description', models.TextField(max_length=100, null=True)),
                ('user_desc', models.TextField(max_length=1000, null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('category', models.CharField(choices=[('clean', 'Погрижи се природата'), ('photo', 'Снимай'), ('observe', 'Научи за фауната')], default='photo', max_length=20)),
                ('date_assigned', models.DateField(blank=True, null=True)),
                ('reward', models.PositiveIntegerField(default=10)),
                ('is_daily', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_first_login', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('has_been_approved', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(default=beaches.models.default_rating)),
                ('has_lifeguard', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_paid_parking', models.BooleanField(default=False)),
                ('has_toilets', models.BooleanField(default=False)),
                ('has_changing_rooms', models.BooleanField(default=False)),
                ('has_paid_zone', models.BooleanField(default=False)),
                ('has_beach_bar', models.BooleanField(default=False)),
                ('favourites', models.ManyToManyField(blank=True, related_name='favourite_beaches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BeachImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='beach_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('beach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beaches.beach')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BeachLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('crowd_level', models.CharField(blank=True, choices=[('Високо', 'high'), ('Средно', 'medium'), ('Ниско', 'low')], default='medium', max_length=20)),
                ('water_clarity', models.CharField(blank=True, choices=[('Облачна', 'cloudy'), ('Мътна', 'murky'), ('Ясна', 'clear')], default='clear', max_length=20)),
                ('water_temp', models.CharField(blank=True, choices=[('Гореща', 'hot'), ('Топла', 'warm'), ('Нормална', 'normal'), ('Хладна', 'cool'), ('Студена', 'cold')], default='normal', max_length=20)),
                ('weather', models.CharField(blank=True, choices=[('Горещо', 'hot'), ('Топло', 'warm'), ('Нормално', 'normal'), ('Хладко', 'cool'), ('Студено', 'cold')], default='normal', max_length=20)),
                ('algae', models.CharField(blank=True, choices=[('Много', 'high'), ('Средно', 'medium'), ('Малко', 'low'), ('Няма', 'none')], default='low', max_length=20)),
                ('kids', models.CharField(blank=True, choices=[('Много', 'high'), ('Средно', 'medium'), ('Малко', 'low'), ('Няма', 'none')], default='low', max_length=20)),
                ('waves', models.CharField(blank=True, choices=[('Големи', 'high'), ('Средни', 'medium'), ('Малки', 'small')], default='low', max_length=20)),
                ('parking_space', models.CharField(blank=True, choices=[('Много', 'high'), ('Средно', 'medium'), ('Малко', 'low'), ('Няма', 'none')], default='low', max_length=20)),
                ('note', models.TextField(blank=True, max_length=300)),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaches.beach')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beaches.beachimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BeachReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('inc_loc', 'Неправилно местоположение'), ('inc_info', 'Неточна информация'), ('ins_cont', 'Обидна информация'), ('other', 'Друго')], max_length=21)),
                ('resolved', models.BooleanField(default=False)),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaches.beach')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=150, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='profile_images/default.svg', null=True, upload_to='profile_images/')),
                ('lat', models.CharField(blank=True, default=48.8566, null=True)),
                ('lng', models.CharField(blank=True, default=2.3522, null=True)),
                ('xp', models.IntegerField(default=0)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('theme', models.CharField(blank=True, default='light', null=True)),
                ('send_notifs', models.BooleanField(blank=True, default=True, null=True)),
                ('language', models.CharField(choices=[('bg', 'Български'), ('en', 'Английски')], default='bg')),
                ('tasks', models.ManyToManyField(blank=True, related_name='assigned_users', to='beaches.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='beaches.userprofile')),
            ],
            options={
                'unique_together': {('user', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AcceptedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unaccepted', 'Неизбрано'), ('accepted', 'В прогрес'), ('completed', 'Завършено')], default='accepted', max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='task_proofs/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaches.task')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaches.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'task')},
            },
        ),
    ]
