# Generated by Django 5.2.5 on 2025-09-25 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('reward', models.PositiveSmallIntegerField()),
                ('tag', models.CharField(choices=[('contribution', 'Принос'), ('review', 'Мнение')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'В прогрес'), ('completed', 'Завършено')], default='accepted', max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaches.userprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaches.task')),
            ],
            options={
                'unique_together': {('user_profile', 'task')},
            },
        ),
    ]
