# Generated by Django 5.2 on 2025-08-27 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0002_userprofile_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeachLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longtitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beaches.beachlocation')),
            ],
        ),
        migrations.CreateModel(
            name='BeachLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('crowd_level', models.CharField(blank=True, choices=[('low', 'Ниско'), ('meduim', 'Средно'), ('high', 'Високо')], default='meduim', max_length=20)),
                ('water_clarity', models.CharField(blank=True, choices=[('clear', 'Ясна'), ('murky', 'Мътна'), ('cloudy', 'Облачна')], default='clear', max_length=20)),
                ('water_temp', models.CharField(blank=True, choices=[('cold', 'Студена'), ('cool', 'Хладна'), ('normal', 'Нормална'), ('warm', 'Топла'), ('hot', 'Гореща')], default='normal', max_length=20)),
                ('weather', models.CharField(blank=True, choices=[('cold', 'Студено'), ('cool', 'Хладно'), ('normal', 'Нормално'), ('warm', 'Топло'), ('hot', 'Горещо')], default='normal', max_length=20)),
                ('algae', models.CharField(blank=True, choices=[('none', 'Няма'), ('low', 'Малко'), ('medium', 'Средно'), ('high', 'Много')], default='low', max_length=20)),
                ('kids', models.CharField(blank=True, choices=[('none', 'Няма'), ('low', 'Малко'), ('medium', 'Средно'), ('high', 'Много')], default='low', max_length=20)),
                ('waves', models.CharField(blank=True, choices=[('small', 'Малки'), ('medium', 'Средни'), ('high', 'Големи')], default='low', max_length=20)),
                ('note', models.TextField(blank=True, max_length=300)),
                ('has_lifegard', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_paid_parking', models.BooleanField(default=False)),
                ('parking_space', models.CharField(blank=True, choices=[('none', 'Няма'), ('low', 'Малко'), ('medium', 'Средно'), ('high', 'Много')], default='low', max_length=20)),
                ('has_toitlets', models.BooleanField(default=False)),
                ('has_changing_rooms', models.BooleanField(default=False)),
                ('has_paid_zone', models.BooleanField(default=False)),
                ('has_beach_bar', models.BooleanField(default=False)),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaches.beach')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaches.userprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
