# Generated by Django 5.2.5 on 2025-10-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0002_task_acceptedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
