# Generated by Django 5.2 on 2025-08-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0003_beachlocation_beach_beachlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beachlocation',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
