# Generated by Django 5.2 on 2025-10-11 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='beach',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourite_beaches', to=settings.AUTH_USER_MODEL),
        ),
    ]
