# Generated by Django 5.2.5 on 2025-08-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0004_rename_longtitude_beachlocation_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beach',
            name='id',
            field=models.UUIDField(default='iykxrtph63xcmlnx6v7pzocrwm30sxvg', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beachlocation',
            name='id',
            field=models.UUIDField(default='5wm692aeq5ea9jn19ctgo3qay2dpde7s', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beachlog',
            name='id',
            field=models.UUIDField(default='m92ibmex02h7gwotx718ynacvlhblubm', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default='x2twsr1e72f395l9nzywdiu41zmkf43y', editable=False, primary_key=True, serialize=False),
        ),
    ]
