# Generated by Django 5.2 on 2025-08-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0006_alter_beach_id_alter_beachlocation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beachlog',
            name='has_beach_bar',
        ),
        migrations.RemoveField(
            model_name='beachlog',
            name='has_changing_rooms',
        ),
        migrations.RemoveField(
            model_name='beachlog',
            name='has_lifegard',
        ),
        migrations.RemoveField(
            model_name='beachlog',
            name='has_paid_parking',
        ),
        migrations.RemoveField(
            model_name='beachlog',
            name='has_paid_zone',
        ),
        migrations.RemoveField(
            model_name='beachlog',
            name='has_parking',
        ),
        migrations.RemoveField(
            model_name='beachlog',
            name='has_toitlets',
        ),
        migrations.AddField(
            model_name='beach',
            name='has_beach_bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beach',
            name='has_changing_rooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beach',
            name='has_lifegard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beach',
            name='has_paid_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beach',
            name='has_paid_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beach',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beach',
            name='has_toitlets',
            field=models.BooleanField(default=False),
        ),
    ]
