# Generated by Django 5.2.5 on 2025-08-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0007_remove_beachlog_has_beach_bar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beach',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='beach',
            name='has_been_aproved',
            field=models.BooleanField(default=False),
        ),
    ]
