# Generated by Django 5.2.5 on 2025-08-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0009_moderatorprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beach',
            old_name='has_lifegard',
            new_name='has_lifeguard',
        ),
        migrations.RenameField(
            model_name='beach',
            old_name='has_toitlets',
            new_name='has_toilets',
        ),
    ]
