# Generated by Django 5.2.5 on 2025-08-29 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0010_rename_has_lifegard_beach_has_lifeguard_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beach',
            old_name='has_been_aproved',
            new_name='has_been_approved',
        ),
    ]
