# Generated by Django 5.2 on 2025-08-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0011_rename_has_been_aproved_beach_has_been_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beach',
            name='location',
        ),
        migrations.AddField(
            model_name='beach',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beach',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BeachLocation',
        ),
    ]
