# Generated by Django 5.2 on 2025-08-29 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0012_remove_beach_location_beach_latitude_beach_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='beach',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BeachReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('Друго', 'other'), ('Грещно местоположение', 'inc_loc'), ('Обидно съдържание', 'ins_cont'), ('Неправилна информация', 'inc_info')], max_length=21)),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaches.beach')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
