# Generated by Django 5.2.5 on 2025-09-02 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0013_badge_beach_approved_date_userprofile_xp_beachreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='beachreport',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='beachreport',
            name='category',
            field=models.CharField(choices=[('inc_loc', 'Неправилно местоположение'), ('inc_info', 'Неточна информация'), ('ins_cont', 'Обидна информация'), ('other', 'Друго')], max_length=21),
        ),
        migrations.CreateModel(
            name='BeachImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaches.userprofile')),
            ],
        ),
    ]
