# Generated by Django 5.2.5 on 2025-09-02 09:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0014_beachreport_resolved_alter_beachreport_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachreport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
