# Generated by Django 5.2.5 on 2025-09-03 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0016_alter_beachimage_user_alter_beachlog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beachimage',
            name='beach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beaches.beach'),
        ),
    ]
