# Generated by Django 5.2 on 2025-09-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0017_beachimage_beach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachlog',
            name='algae',
            field=models.CharField(blank=True, choices=[('Много', 'high'), ('Средно', 'medium'), ('Малко', 'low'), ('Няма', 'none')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='beachlog',
            name='crowd_level',
            field=models.CharField(blank=True, choices=[('Високо', 'high'), ('Средно', 'meduim'), ('Ниско', 'low')], default='meduim', max_length=20),
        ),
        migrations.AlterField(
            model_name='beachlog',
            name='kids',
            field=models.CharField(blank=True, choices=[('Много', 'high'), ('Средно', 'medium'), ('Малко', 'low'), ('Няма', 'none')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='beachlog',
            name='parking_space',
            field=models.CharField(blank=True, choices=[('Много', 'high'), ('Средно', 'medium'), ('Малко', 'low'), ('Няма', 'none')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='beachlog',
            name='water_clarity',
            field=models.CharField(blank=True, choices=[('Облачна', 'cloudy'), ('Мътна', 'murky'), ('Ясна', 'clear')], default='clear', max_length=20),
        ),
        migrations.AlterField(
            model_name='beachlog',
            name='water_temp',
            field=models.CharField(blank=True, choices=[('Гореща', 'hot'), ('Топла', 'warm'), ('Нормална', 'normal'), ('Хладна', 'cool'), ('Студена', 'cold')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='beachlog',
            name='waves',
            field=models.CharField(blank=True, choices=[('Големи', 'high'), ('Средни', 'medium'), ('Малки', 'small')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='beachlog',
            name='weather',
            field=models.CharField(blank=True, choices=[('Горещо', 'hot'), ('Топло', 'warm'), ('Нормално', 'normal'), ('Хладно', 'cool'), ('Студено', 'cold')], default='normal', max_length=20),
        ),
    ]
