# Generated by Django 5.2 on 2025-09-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0018_alter_beachlog_algae_alter_beachlog_crowd_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lat',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lng',
            field=models.CharField(blank=True, null=True),
        ),
    ]
