# Generated by Django 5.2 on 2025-09-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0019_userprofile_lat_userprofile_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachimage',
            name='image',
            field=models.ImageField(upload_to='static/beach_images/'),
        ),
    ]
