# Generated by Django 5.2 on 2025-09-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0020_alter_beachimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lat',
            field=models.CharField(blank=True, default=48.8566, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lng',
            field=models.CharField(blank=True, default=2.3522, null=True),
        ),
    ]
